#!/usr/bin/env python3
"""
Test script for the slicing animation functionality.

This script tests the new visualization components with real diffuse
scattering data generated by run_torch.py.
"""

import numpy as np
import logging
import sys
from pathlib import Path

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def test_slicing_animation():
    """Test the slicing animation with real data."""
    
    # Import the visualization components
    try:
        from eryx.visualization.core import IntensityDataHandler, NaNProcessor
        from eryx.visualization.slicing.animator import SlicingAnimator, create_slicing_animation
        from eryx.visualization.slicing.plane_calculator import PlaneCalculator
        logger.info("Successfully imported visualization components")
    except ImportError as e:
        logger.error(f"Failed to import visualization components: {e}")
        return False
    
    # Check for data file
    data_file = "torch_grid_results.npz"
    if not Path(data_file).exists():
        logger.error(f"Data file {data_file} not found. Run 'python run_torch.py' first.")
        return False
    
    logger.info(f"Loading data from {data_file}")
    
    # Test 1: Load and inspect data
    try:
        handler = IntensityDataHandler(data_file)
        q_vectors, intensity, map_shape = handler.load_data()
        
        if intensity is None:
            logger.error("Failed to load intensity data")
            return False
        
        logger.info(f"Loaded intensity data: shape {intensity.shape}, map_shape {map_shape}")
        
        # Get statistics
        stats = handler.get_statistics()
        logger.info(f"Data statistics: {stats['n_valid']} valid, {stats['n_nan']} NaN")
        logger.info(f"Intensity range: [{stats['min']:.3e}, {stats['max']:.3e}]")
        
    except Exception as e:
        logger.error(f"Failed to load data: {e}")
        return False
    
    # Test 2: Test PlaneCalculator
    try:
        if intensity.ndim == 1:
            # Need to reshape
            handler.reshape_to_3d(force=True)
            intensity = handler.intensity
            logger.info(f"Reshaped to 3D: {intensity.shape}")
        
        calculator = PlaneCalculator(intensity.shape)
        
        # Test plane creation
        normal = np.array([1, 1, 1])
        plane = calculator.calculate_plane_position(normal, distance=5.0)
        logger.info(f"Created plane with normal {normal}: {plane}")
        
        # Test cutting sequence
        planes = calculator.create_cutting_sequence(normal, n_frames=10)
        logger.info(f"Created sequence of {len(planes)} planes")
        
    except Exception as e:
        logger.error(f"PlaneCalculator test failed: {e}")
        return False
    
    # Test 3: Process NaN values
    try:
        # Try different NaN strategies
        processed = NaNProcessor.apply_strategy(intensity, 'interpolate')
        logger.info(f"Processed NaN values with interpolation")
        
        # Check if NaNs were handled
        n_nan_after = np.sum(np.isnan(processed))
        logger.info(f"NaN values after processing: {n_nan_after}")
        
    except Exception as e:
        logger.error(f"NaN processing failed: {e}")
        processed = intensity  # Use original
    
    # Test 4: Create simple animation
    try:
        logger.info("Creating test animation...")
        
        # Use processed data
        animator = SlicingAnimator(processed)
        
        # Generate a small test animation
        frames = animator.generate_animation(
            normal=[1, 1, 1],
            n_frames=10,  # Small number for testing
            subsample=8,  # Heavy subsampling for speed
            figsize=(8, 6),
            dpi=50,  # Lower resolution for testing
            show_plane=True,
            show_volume=True,
            colorbar=False  # Skip colorbar for speed
        )
        
        logger.info(f"Generated {len(frames)} frames")
        
        # Save as GIF
        output_path = "test_slicing.gif"
        animator.export(output_path, fps=5)
        logger.info(f"Saved test animation to {output_path}")
        
    except Exception as e:
        logger.error(f"Animation creation failed: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    # Test 5: Use high-level API
    try:
        logger.info("Testing high-level API...")
        
        output = create_slicing_animation(
            data_file,
            normal=[0, 0, 1],  # Slice along Z axis
            n_frames=15,
            output_path="test_z_slice.gif",
            nan_strategy='interpolate',
            fps=5,
            subsample=8,
            figsize=(8, 6),
            dpi=75
        )
        
        logger.info(f"Created animation with high-level API: {output}")
        
    except Exception as e:
        logger.error(f"High-level API test failed: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    logger.info("All tests completed successfully!")
    return True

if __name__ == "__main__":
    success = test_slicing_animation()
    sys.exit(0 if success else 1)