import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re # Import regular expressions

# --- 1. Load the extracted data ---
try:
    df = pd.read_csv("extracted_data.csv")
except FileNotFoundError:
    print("Error: extracted_data.csv not found. Please run extract_cbf_metadata.py first.")
    exit()

if df.empty:
    print("extracted_data.csv is empty.")
    exit()

print("Original DataFrame head:")
print(df.head().to_string())

# --- 2. Parse 'array_data.header_contents' ---
def parse_pilatus_header(header_string):
    if pd.isna(header_string) or not isinstance(header_string, str):
        return {}
    
    parsed_data = {}
    # Regex to capture:
    # Group 1: The key (non-greedy, up to a colon or equals sign or end of key-like part)
    # Group 2: The value (everything after the key/colon/equals)
    # This pattern is more flexible with or without colon, and with '='
    key_value_pattern = re.compile(r"^\s*#\s*([^:=]+?)\s*[:=]?\s*(.*)$")
    beam_xy_pattern = re.compile(r"Beam_xy\s*\(([^,]+),\s*([^)]+)\)")

    for line in header_string.splitlines():
        line_content = line.strip()
        if not line_content.startswith("#"):
            continue
        
        line_content_no_hash = line_content[1:].strip()

        # Special handling for timestamp (if it doesn't fit key:value)
        if re.match(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}", line_content_no_hash):
            parsed_data["timestamp_header"] = line_content_no_hash
            continue

        # Try to match Beam_xy
        beam_match = beam_xy_pattern.search(line_content_no_hash)
        if beam_match:
            try:
                parsed_data["beam_x_header"] = float(beam_match.group(1).strip())
                parsed_data["beam_y_header"] = float(beam_match.group(2).strip())
            except ValueError:
                parsed_data["beam_x_header"] = beam_match.group(1).strip() # Store as string if not float
                parsed_data["beam_y_header"] = beam_match.group(2).strip()
            continue # Move to next line after handling Beam_xy

        # General key-value parsing with more flexible pattern
        match = key_value_pattern.match(line_content)
        if match:
            key = match.group(1).strip()
            value = match.group(2).strip()
            
            # Further clean value if it's something like "autog (vrf = 1.000)" -> "autog"
            if "(" in value and ")" in value:
                value_before_paren = value.split("(",1)[0].strip()
                if value_before_paren: # If there's content before parenthesis
                    value = value_before_paren

            # Clean up key: lowercase, replace space, hyphen, and period with underscore
            clean_key = key.lower().replace(" ", "_").replace("-", "_").replace(".", "_")
            
            # Handle special case like "Pixel_size 172e-6 m x 172e-6 m"
            if clean_key == "pixel_size" and "m x" in value:
                try:
                    # Extract the first numeric part for pixel_size_x and pixel_size_y
                    numeric_part = re.match(r'([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)', value)
                    if numeric_part:
                        parsed_data["pixel_size_x"] = numeric_part.group(1)
                        parsed_data["pixel_size_y"] = numeric_part.group(1) # Assuming square pixels
                except:
                    parsed_data[clean_key] = value # fallback
            elif clean_key: # Ensure key is not empty
                parsed_data[clean_key] = value
        # else:
            # print(f"Debug: Line not parsed by key-value: '{line_content}'")

    return parsed_data

header_details_df = df['array_data.header_contents'].apply(parse_pilatus_header).apply(pd.Series)
df = pd.concat([df.drop(columns=['array_data.header_contents'], errors='ignore'), header_details_df], axis=1)


print("\nDataFrame head after parsing header_contents:")
print(df.head().to_string())
print("\nAvailable columns after parsing:", df.columns.tolist())

# --- 3. Convert relevant parsed columns to numeric ---
# These names should now match the keys generated by the improved parser
cols_to_convert_numeric = [
    'pixel_size', 
    'silicon_sensor,_thickness', # This key itself is problematic due to comma
    'exposure_time',
    'exposure_period',
    'tau',
    'count_cutoff',
    'threshold_setting',
    'wavelength',
    'detector_distance',
    'beam_x_header', # Already float from parser if possible
    'beam_y_header', # Already float from parser if possible
    'start_angle',
    'angle_increment',
    'phi',
    'n_oscillations',
    'shutter_time',
    'n_excluded_pixels' # Added this as it looks numeric
]

# Special handling for 'silicon_sensor,_thickness' due to comma in original key
if 'silicon_sensor,_thickness' in df.columns:
    df.rename(columns={'silicon_sensor,_thickness': 'silicon_sensor_thickness'}, inplace=True)
    if 'silicon_sensor_thickness' not in cols_to_convert_numeric:
         cols_to_convert_numeric.append('silicon_sensor_thickness')


for col in cols_to_convert_numeric:
    if col in df.columns:
        if df[col].dtype == 'object' or isinstance(df[col].iloc[0], str) : # Check if conversion is needed
            # Attempt to extract only the first numeric part (handles units like "0.1 s" or "100 counts")
            df[col] = df[col].astype(str).str.extract(r'^\s*([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)\b')[0]
        df[col] = pd.to_numeric(df[col], errors='coerce')
        print(f"Info: Column '{col}' converted/attempted to numeric.")
    # else:
    #     print(f"Info: Column '{col}' for numeric conversion not found in parsed header.")


print("\nDataFrame head after numeric conversion of header fields:")
print(df.head().to_string())
print("\nData types after numeric conversion:")
print(df.dtypes)


# --- 4. Visualization Examples ---

# Example 1: Histogram of a numeric field (e.g., exposure_time)
if 'exposure_time' in df.columns and df['exposure_time'].notna().any():
    plt.figure(figsize=(8, 6))
    df['exposure_time'].dropna().hist(bins=10) # Reduced bins for single value
    plt.title('Distribution of Exposure Time (from header)')
    plt.xlabel('Exposure Time (s)')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.savefig("exposure_time_histogram.png")
    print("\nSaved exposure_time_histogram.png")
    # plt.show()
else:
    print("\n'exposure_time' column not found or all NaN, skipping histogram.")

# Example 2: Scatter plot of two numeric fields (e.g., detector_distance vs wavelength)
if 'detector_distance' in df.columns and 'wavelength' in df.columns and \
   df['detector_distance'].notna().any() and df['wavelength'].notna().any():
    plt.figure(figsize=(8, 6))
    # Since you have only 1 file, scatter will be a single point
    plt.scatter(df['wavelength'].dropna(), df['detector_distance'].dropna(), alpha=0.5, s=50)
    plt.title('Detector Distance vs. Wavelength (from header)')
    plt.xlabel('Wavelength (A)')
    plt.ylabel('Detector Distance (m)')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("distance_vs_wavelength_scatter.png")
    print("Saved distance_vs_wavelength_scatter.png")
    # plt.show()
else:
    print("\n'detector_distance' or 'wavelength' not found or all NaN, skipping scatter plot.")


# Example 3: Heatmap (using fields parsed from header)
heatmap_x_col = 'wavelength'
heatmap_y_col = 'detector_distance'
heatmap_val_col = 'exposure_time' 

print(f"\nAttempting heatmap with X='{heatmap_x_col}', Y='{heatmap_y_col}', Value='{heatmap_val_col}'")

if heatmap_x_col in df.columns and heatmap_y_col in df.columns:
    df_plot = df.copy()
    
    df_plot_cleaned = df_plot.dropna(subset=[heatmap_x_col, heatmap_y_col])

    if heatmap_val_col and heatmap_val_col in df_plot_cleaned.columns:
        df_plot_cleaned = df_plot_cleaned.dropna(subset=[heatmap_val_col])
        agg_func = 'mean'
        agg_label = f"{agg_func} of {heatmap_val_col}"
        fmt_str = ".3f" # Adjusted for typical exposure times
    else: 
        agg_func = 'size'
        agg_label = "Count"
        fmt_str = "d"
        heatmap_val_col = None # Ensure pivot_table gets None if no value column

    if not df_plot_cleaned.empty:
        try:
            pivot_x_col = heatmap_x_col
            if df_plot_cleaned[heatmap_x_col].nunique() > 15 and pd.api.types.is_numeric_dtype(df_plot_cleaned[heatmap_x_col]):
                df_plot_cleaned[heatmap_x_col + '_binned'] = pd.cut(df_plot_cleaned[heatmap_x_col], bins=min(10, df_plot_cleaned[heatmap_x_col].nunique()), duplicates='drop')
                pivot_x_col = heatmap_x_col + '_binned'
            
            pivot_y_col = heatmap_y_col
            if df_plot_cleaned[heatmap_y_col].nunique() > 15 and pd.api.types.is_numeric_dtype(df_plot_cleaned[heatmap_y_col]):
                df_plot_cleaned[heatmap_y_col + '_binned'] = pd.cut(df_plot_cleaned[heatmap_y_col], bins=min(10, df_plot_cleaned[heatmap_y_col].nunique()), duplicates='drop')
                pivot_y_col = heatmap_y_col + '_binned'

            pivot_data = pd.pivot_table(
                df_plot_cleaned,
                values=heatmap_val_col, # Will be None if agg_func is 'size'
                index=pivot_y_col,
                columns=pivot_x_col,
                aggfunc=agg_func,
                fill_value=0 if agg_func == 'size' else np.nan
            )

            if not pivot_data.empty:
                plt.figure(figsize=(max(8, pivot_data.shape[1]*0.8), max(6, pivot_data.shape[0]*0.6))) # Dynamic size
                sns.heatmap(pivot_data, annot=True, fmt=fmt_str, cmap="viridis", cbar_kws={'label': agg_label})
                plt.title(f"Heatmap of {heatmap_y_col} vs {heatmap_x_col}")
                plt.xlabel(heatmap_x_col)
                plt.ylabel(heatmap_y_col)
                plt.xticks(rotation=45, ha="right")
                plt.yticks(rotation=0)
                plt.tight_layout()
                plt.savefig("parsed_header_heatmap.png")
                print("Saved parsed_header_heatmap.png")
                # plt.show()
            else:
                print("Pivot table for heatmap is empty after processing.")
        except Exception as e:
            print(f"Error generating heatmap from parsed header: {e}")
            import traceback
            traceback.print_exc()
    else:
        print(f"\nSkipping heatmap: Not enough data after cleaning for columns '{heatmap_x_col}', '{heatmap_y_col}'" + (f", '{heatmap_val_col}'" if heatmap_val_col else "") + ".")
else:
    missing_heatmap_cols = []
    if heatmap_x_col not in df.columns: missing_heatmap_cols.append(heatmap_x_col)
    if heatmap_y_col not in df.columns: missing_heatmap_cols.append(heatmap_y_col)
    print(f"\nSkipping heatmap: One or more required columns ({', '.join(missing_heatmap_cols)}) not found in DataFrame.")
